SUCCESS            = 0
INCORRECT_PASSWORD = 1
PERMISSION_ERROR   = 2
SSH_ERROR          = 3
MISSING_COMMAND    = 4
ROUTER_OVERLOADED  = 5
INVALID_ROUTER     = 6
INVALID_ARGUMENTS  = 7

ROUTER_SESSIONS   = Hash.new